STOCK_NAME_APPLE = "APPL"
STOCK_NAME_BTC = "BTC"
STOCK_NAME_CSCO = "CSCO"
STOCK_NAME_MSFT = "MSFT"
STOCK_NAME_QCOM = "QCOM"
STOCK_NAME_SBUX = "SBUX"

STOCK_NAMES = [
    STOCK_NAME_APPLE,
    STOCK_NAME_CSCO,
    STOCK_NAME_MSFT,
    STOCK_NAME_QCOM,
    STOCK_NAME_SBUX
]

